### ISSUE TITLE
Linux下无法显示

### ISSUE THREAD

**Issue by MichaelZhao0517** [Lanseria/vue-pdf-useinvite#4]
大佬汇报一个问题啊，这个在windows下显示正常，在linux（Ubuntu20）下，无法显示，试过自带的火狐和chrome，都无法显示，请教可以解决吗？
---后来发现应该是linux连得内网，里面有导入网络包http://unpkg.zhimg.com/pdfjs-dist@2.9.359/build/pdf.worker.min.js的缘故，请问有方法可以不联网使用这个组件吗？

**Comment by lanseria** [comment]
这应该跟系统没关系把😅

**Comment by MichaelZhao0517** [comment]
是的，和Linux没有关系，我windows断网了一样，我试着下载pdf.worker.min.js放本地替换你js文件里的url，但是不起作用。。。

**Comment by lanseria** [comment]
> 是的，和Linux没有关系，我windows断网了一样，我试着下载pdf.worker.min.js放本地替换你js文件里的url，但是不起作用。。。

参考这个我修复了，你可以重新install 一下，tag v1.0.5 https://github.com/mozilla/pdf.js/issues/8204

**Comment by MichaelZhao0517** [comment]
不好意思，我原来安装的是1.0.3 没有问题，升到1.0.5后出现了下面的错误，无法显示，后来我退到了1.0.4发现也是一样的错误，最后我退到1.0.3又可以显示正常了。。。
runtime-core.esm-bundler.js:6591 [Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 

at  PdfEditor src="/bpi/workfolder/uploads/store/22/22.pdf" 
at  Performance onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > 

上面用的是pdf-editor, 换成pdf-viewer直接报错， 1.0.3 两个都正常的
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js:6561:34)
    at vue-pdf-vite.es.js:73634:13
    at normalizeChildren (runtime-core.esm-bundler.js:6408:42)
    at createBaseVNode (runtime-core.esm-bundler.js:6170:9)
    at _createVNode (runtime-core.esm-bundler.js:6263:12)
    at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:6128:12)
    at Proxy._sfc_render$4 (vue-pdf-vite.es.js:73627:5)
    at renderComponentRoot (runtime-core.esm-bundler.js:464:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4233:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)

**Comment by lanseria** [comment]
我这里测试没什么问题，不管在viewer还是edit上，你可以尝试 yarn upgrade-interactive 同时升级vue3的版本以及其编译器runtime
```
 "dependencies": {
    "@lanseria/vue-pdf-vite": "^1.0.0",
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "typescript": "^4.3.2",
    "vite": "^2.3.8",
    "vue-tsc": "^0.0.24"
```
如果还是不行我也没办法了，
你可以fork仓库自行引入使用
